fragment platformFields on DataPlatform {
  urn
  name
  __typename
}

fragment query on QueryEntity {
  urn
  properties {
    name
    description
    source
    statement {
      value
      language
    }
    # created {
    #   time
    #   actor
    # }
    lastModified {
      # time
      actor
    }
  }
  platform {
    ...platformFields
  }
  subjects {
    dataset {
      urn
      type
      ... on Dataset {
        name
      }
    }
    schemaField {            #[NEWER_GMS]
      urn                    #[NEWER_GMS]
      type                   #[NEWER_GMS]
      fieldPath              #[NEWER_GMS]
    }                        #[NEWER_GMS]
  }
}

query listQueries($input: ListQueriesInput!) {
  listQueries(input: $input) {
    start
    total
    count
    queries {
      ...query
    }
  }
}
